<?php

// ::ZETA-PRODUCER-NO-COMPRESSION::

require_once('../afx.inc.php');

$loginController = new ZpsBackendServerProjectStatusController();
$viewBag = $loginController->HandleGetOrPost();

/**
 * @var ZpsBackendProjectStateModel $model
 */
$model = $viewBag['model'];

$title = "Projektstatus";

// --

$colLabel = "col-xs-12 col-sm-12 col-md-12";
$colEditor = "col-xs-12 col-sm-12 col-md-12";
$colEditorB = "col-xs-12 col-sm-12 col-sm-offset-0 col-md-12 col-md-offset-0";

/*$viewBag['additional_header'] = "<meta http-equiv=\"refresh\" content=\"300\" />";*/
?>

<?php require_once('_header.php') ?>

<!-- ##################################################################### -->

<script>
    var fetchUrl = '<?=UrlHelper::SetParameters("api.php", array(
                    "action" => "get-project-state")) ?>';
</script>

<script>
    var fetchTimerId = 0;

    $(function () {
        $('#confirm').focus();

        fetchTimerId = window.setTimeout(fetchState, 1000);
        window.setTimeout(hideNotify, 5000);
    });

    function fetchState() {
        $.ajax({
            type: "GET",
            url: fetchUrl,
            dataType: "JSON",
            success: function (data) {
                $('#stateControl').html(data.state);

                window.clearTimeout(fetchTimerId);
                fetchTimerId = window.setTimeout(fetchState, 1000);
            },
            error: function () {
                window.clearTimeout(fetchTimerId);
                fetchTimerId = window.setTimeout(fetchState, 1000);
            }
        })
    }

    function hideNotify() {
        $('#success-panel').hide();
    }
</script>

<div class="row delta-y-before-2">
    <div class="col-md-8 col-xs-12">
        Sollte sich Ihr Projekt nicht mehr vom Server downloaden lassen oder nicht mehr auf den Server hochladen lassen,
            z.&nbsp;B. weil ein Upload/Download abgebrochen ist, so k&ouml;nnen Sie es hier auf einen definierten Anfangszustand setzen.
    </div>
</div>

<div class="row delta-y-before-2 form-group">
    <div class="<?=$colLabel?>">
        <label>Aktuelles Projekt</label>
    </div>
    <div class="<?=$colEditor?>">
        <div id="stateControl" class="project-status-box">
            <?=$model->UserReadableState?>
        </div>
    </div>
</div>

<!-- ######################################################################### -->

<div class="row delta-y-before-1 form-group" id="pinginfos"
    <?php if ( sizeof($model->UserReadablePingActionInfos) <= 0) { ?> style="display: none" <?php } ?>>
    <div class="<?=$colLabel?>">
        <label>Aktuelle Ping-Infos</label>
    </div>
    <div class="<?=$colEditor?>">
        <div id="stateControl" class="project-status-box">
            <?php foreach($model->UserReadablePingActionInfos as $pingActionInfo) { ?>
            <div class="ping-info-block">
                <div>
                    ID: <?=$pingActionInfo['id']?>
                </div>
                <div>
                    Date created: <?=$pingActionInfo['dateCreatedFormatted']?>
                </div>
                <div>
                    Generated by client with token: <?=$pingActionInfo['generatedByClientToken']?>
                </div>
                <div>
                    Generated by client with instance token: <?=$pingActionInfo['generatedByInstanceToken']?>
                </div>
                <div>
                    Action: <?=$pingActionInfo['action']?>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

<!-- ######################################################################### -->

<form method="post" action="<?=UrlHelper::GetCurrentFullUrl()?>">
    <!---
        <div class="row delta-y-before-2 <?=ArrayHelper::GetValue($viewBag, 'confirm.class')?> form-group">
            <div class="col-md-12">
                <input type="checkbox" id="confirm" name="confirm" class="form-checkbox" checked="checked" />
                <label for="confirm">Ja, Projekt zur&uuml;cksetzen</label>
            </div>
            <?php if ( ArrayHelper::HasValue($viewBag, 'confirm.error') ) { ?>
            <div class="col-md-12 error-text">
                <?=$viewBag['confirm.error']?>
            </div>
            <?php } ?>
        </div>
        -->

    <div class="row delta-y-before-2">
        <div class="col-md-12">
            <input class="btn btn-default btn-primary" type="submit" value="Projekt zur&uuml;cksetzen" />
            <a href="<?=$viewBag['cancelUrl']?>" class="btn btn-default">Zur&uuml;ck</a>
        </div>
    </div>
</form>

<!-- ##################################################################### -->
<?php require_once('_footer.php') ?>
